### ISSUE TITLE
Issue with add-on-export yaml filed

### ISSUE THREAD

**Issue by steveyiyo** [natesales/pathvector#125]
**Describe the bug**
I can't use `add-on-export` and `add-on-import` in configure file, and it returns the below error message.
```
FATA[0000] YAML unmarshal: yaml: unmarshal errors:
  line 119: field add-on-import not found in type config.Peer 
```

**Environment**
1. Pathvector 5.12.0 commit f3ecd92e6976f21c3567f4938923e2604617ee4f date 2022-05-21T06:36:09Z
No plugins
2. Debian 11
3. `add-on-export: [ "7034,8000" ]`

**Comment by natesales** [comment]
`add-on-export` and `add-on-import` were renamed in version 6 from import/export communities. We're almost ready to tag v6.0 stable, but for now there is a beta at https://github.com/natesales/pathvector/releases/tag/v6.0.0-beta.3
