### ISSUE TITLE
Import RPKI valid routes via function or parameter per peer

### ISSUE THREAD

**Issue by ernstjo** [natesales/pathvector#126]
I would be a good feature to allow per peer the import of RPKI ROA_VALID routes automatically. So, that filters are working based on RPKI valid routes but also in the case of the use of irr filtering.

At the moment it is not possible to place it before $peer.FilterIRR only after IRR filter function. That means that RPKI valid but without IRR objects are not passed into the route table.

At the moment this is not the case:

`function allow_rpki_valid() {
  {{ if .RPKIEnable }}
  if (net.type = NET_IP4) then {
    if (roa_check(rpki4, net, bgp_path.last_nonaggregated) == ROA_VALID) then accept;
  }

  if (net.type = NET_IP6) then {
    if (roa_check(rpki6, net, bgp_path.last_nonaggregated) == ROA_VALID) then accept;
  }
  {{ end }}
}`

Place function allow_rpki_valid() before IRR filter check.

**Comment by natesales** [comment]
Which version of Pathvector are you referring to? The current HEAD has `reject_rpki_invalid` and `force_rpki_strict` which are "passthrough"; routes can only be rejected within the function, not explicitly allowed.

**Comment by ernstjo** [comment]
Last version, 5.12.0.

Filter will be configured in following setup:

```
            reject_bogon_routes();
            reject_bogon_asns();
            reject_out_of_bounds_routes();
            reject_rpki_invalid();
            enforce_first_as(xxx);
            enforce_peer_nexthop(xxx);
            reject_transit_paths();
            bgp_large_community.delete([(xxx, *, *)]);
            process_blackholes();
            bgp_local_pref = 200; # pathvector:localpref
            honor_graceful_shutdown();
            bgp_large_community.add((xxx,xxx,0));
            bgp_large_community.add((xxx,xxx,8));
            ### new function: accept RPKI valid routes ###
            allow_rpki_valid()
            if (net ~ XXXX_PFX_v6) then { accept; } else { _reject("not in IRR prefix set"); }
            accept;
```

**Comment by natesales** [comment]
Can I see your full config?

**Comment by ernstjo** [comment]
Which config, pathvector.yml or peer config?

I think config will not help, because at the moment pathvector enforce RPKI valids or reject invalids but does not havw an function to accept RPKI valids and not only some in IRR set.

**Comment by natesales** [comment]
I've modified the way BIRD overrides work in df1d2c9e7628803af0222f9dbd928882ab3d1e84.

In your case you can now add the `allow_rpki_valid()` call in `post-import-filter`.

`pre-import-filter`: Configuration to add before the filtering section of the import policy
`post-import-filter`: Configuration to add after the filtering section of the import filter
`pre-import-accept`: Configuration to add immediately before the final accept term import
`pre-export`: Configuration to add before the export policy
`pre-export-final`: Configuration to add after the export policy before the final accept/reject term

This is just in time for v6 - there may be a beta release before the final v6 release, but regardless these changes should work on the current HEAD.
