### ISSUE TITLE
Provide i386 packages for Arista EOS

### ISSUE THREAD

**Issue by samip5** [natesales/pathvector#134]
**Describe the bug**
There is no i386 packages for Arista.

**Environment**

1. `INFO[0000] Pathvector 5.5.2 commit 4c44c80ed53032dbf9a8b16a9bcc57ae16c0fe88 date 2021-09-12T08:55:22Z`
2. Arista EOS 4.15.10M

**To Reproduce**
Try to install new version of Pathvector on Arista switch, and have it fail due to it not being 64-bit.

**Expected behavior**
It would be possible to install newer one.

```
# extension pathvector-arista.swix
% Error installing pathvector-arista.swix: RPM install error: Transaction failed: package pathvector-0:6.0.2-1.x86_64 is intended for a x86_64 architecture

Software image version: 4.15.10M
Architecture:           i386
```

**Comment by natesales** [comment]
Pathvector unfortunately doesn't support 32-bit platforms, so i386 support isn't possible at the moment.
