### ISSUE TITLE
Reenable Mikrotik Docker support 

### ISSUE THREAD

**Issue by ernstjo** [natesales/pathvector#139]
Hey,

Mikrotik supports docker containers again. Can you reenable the build for that platform.
Using it with 2216 and others providing nice hardware and replacing the crappy software :)

Thanks.

Cheers.

**Comment by natesales** [comment]
We've dropped support for Mikrotik given instability on their platform, but the build script still exists if you'd like to try yourself. (See https://github.com/natesales/pathvector/blob/main/vendorbuild/mikrotik/build.sh)
