### ISSUE TITLE
Separate bgpq-args for IPv4 and IPv6

### ISSUE THREAD

**Issue by rapdodge** [natesales/pathvector#144]
**What feature would you like to see?**

Separate `bgpq-args` for IPv4 and IPv6

The one where there is a bgpq4 function that you want to use but it will interfere with one of the IP versions

Example bgpq4 query
```
root@bismillah-norway:~# bgpq4 -Ab6R 48 AS-RAPDODGE
NN = [
    2a06:1287:900::/40{40,48},
    2a06:a005:15d0::/44{44,48},
    2a07:54c2:b00b::/48,
    2a0a:6040:fb00::/40{40,48},
    2a12:dd47:8046::/48,
    2a12:dd47:8700::/40{40,48},
    2a12:dd47:d000::/40{40,48}
];
```
`-R 48` will making le 48 for IPv6, but it will break v4 query
```
root@bismillah-norway:~# bgpq4 -Ab4R 48 AS-CLOUDFLARE
FATAL ERROR:Invalid value for refine(-R): 48 (1-32 for IPv4)
```
Maybe pathvector should making separate `bgpq-args` for v4 and v6

Best regards,

**Comment by peter-pathnetwork** [comment]
+1 for this, main reason being that when IRR filtering is enabled it doesn't take IRR records for the parent subnet and ASN combo into account.

**Comment by peter-potvin** [comment]
+1 for this, main reason being that when IRR filtering is enabled it doesn't take IRR records for the parent subnet and ASN combo into account.

**Comment by l27001** [comment]
+1, but in my opinion good solution for original problem will be separate option like:
```strict-irr: [true|false] - should routes without their own IRR but covered by the parent IRR be dropped?```
And if this option is set to true it will add `-R 48` for v6 and `-R 24` for v4 to bgpq4 query parameters

**Comment by rapdodge** [comment]
> +1, but in my opinion good solution for original problem will be separate option like: `strict-irr: [true|false] - should routes without their own IRR but covered by the parent IRR be dropped?` And if this option is set to true it will add `-R 48` for v6 and `-R 24` for v4 to bgpq4 query parameters

I think this is more nice, 2 layer :D

**Comment by natesales** [comment]
How does this look?

https://github.com/natesales/pathvector/compare/main...irr-accept-child-prefixes

**Comment by rapdodge** [comment]
I think is enough...
Waiting for others response ;D

**Comment by peter-potvin** [comment]
Works for me! Thanks, Nate!

**Comment by l27001** [comment]
Great! Thanks for your work!

**Comment by natesales** [comment]
#145
