### ISSUE TITLE
RFC9234 support

### ISSUE THREAD

**Issue by TheEnbyperor** [natesales/pathvector#156]
[RFC9234](https://www.ietf.org/rfc/rfc9234.html) helps prevent route leaks by assuring both sides of the connection agree on the business relationship in the connection (transit, peering, downstream, etc.)

BIRD since version 2.0.11 implemented RFC9234, it should be possible to define RFC9234 relationships in the Pathvector config and have these output into the generated Bird config.

**Comment by natesales** [comment]
Preliminary role support added in [fe270a5](https://github.com/natesales/pathvector/commit/fe270a5cb94f750938b26314f533b32f6d4b967e)

**Comment by natesales** [comment]
A snapshot release for this feature is available from artifacts on https://github.com/natesales/pathvector/actions/runs/4090842068

**Comment by natesales** [comment]
Added in v6.2.0
