### ISSUE TITLE
BGP Anchor Communities

### ISSUE THREAD

**Issue by bonzi** [natesales/pathvector#160]
**What feature would you like to see?**

Addition of a flag for an additional BGP Community (or multiple) to be added to every announcement.

This is in the same vein as Anchor Prefixes for different sites/DCs announcing Anycast prefixes.

An example of this being implemented can be found at https://faelix.net/ref/as41495/

In my own personal use case, this would be implemented in the scheme of `(ASN, Rule (Locations), Location)`, e.g. `(65510, 3, 1)` for site location ID 1

In essence, it would be up to the network operator to design their own scheme for the community, and the config command would simply enable this community to be added to every announcement.

**Comment by bonzi** [comment]
Apologies if this is hard to understand, Writing isn't my strong suit 🤣

**Comment by natesales** [comment]
[`add-on-export`](https://pathvector.io/docs/configuration#add-on-export) takes a list of communities for Pathvector to add to all exported routes. Does this cover your use case?

**Comment by bonzi** [comment]
Yes, We are currently implementing this like that, However it requires multiple additions to the peer templates.

Realistically this would be a variable that appends to the existing `add-on-export` as those defined in the peer template is for that template only.
