### ISSUE TITLE
BGP Route Dampening

### ISSUE THREAD

**Issue by rapdodge** [natesales/pathvector#162]
**What feature would you like to see?**
Can pathvector setting up BGP Route Dampening features to BIRD2 configuration?
I think implementing BGP Route Dampening is really good idea, since sometimes when configurator did something fatal, it will cause flapping too much :(

**Comment by natesales** [comment]
BIRD (the underlying BGP daemon that Pathvector uses) doesn't currently support route dampening. This would be a feature request for the BIRD team.
