### ISSUE TITLE
Override accepted routes

### ISSUE THREAD

**Issue by rapdodge** [natesales/pathvector#174]
I'm know there is [prefixes](https://pathvector.io/docs/configuration#prefixes-1) feature for accepting prefixes...

But, is there any chances for overriding define for the prefixes to be accept?

An example
AS150a is an upstream of AS150b.
AS150a has 1 prefix of IPv4 address, which is xx3.87.68.0/24
AS150b has 1 prefix of IPv4 address, which is xx3.99.27.0/24

Me, as network administrator of AS150a wanted to setting accepted prefixes manually, not via irr server. But, if I've set `filter-irr: false` and prefixes it's already loaded manually, it's still just blank.

Is there any chances to overriding the define prefix when prefixes is set?

`filter-irr: true`. And there is duplicate for the AS150b prefix.
![image](https://user-images.githubusercontent.com/33513626/235740151-4c712315-9b85-4967-9af0-2e98a9c7215f.png)

`filter-irr: false`. There is no define prefixes.
![image](https://user-images.githubusercontent.com/33513626/235740771-3a3d0631-e85a-4494-8fe6-208d6f25d8cf.png)

Both setting (`filter-irr: false / true`) I've already set the prefixes
![image](https://user-images.githubusercontent.com/33513626/235741903-cef993f2-1ecc-4f68-bbf2-97bc51a442bc.png)

Downstream template
![image](https://user-images.githubusercontent.com/33513626/235742534-db234f13-cdf8-4a24-a237-73f4c11b3f2a.png)

Best regards,

**Comment by natesales** [comment]
Fixed in v6.3.0
