### ISSUE TITLE
Load bogon ASNs from a URL

### ISSUE THREAD

**Issue by lucyrose39** [natesales/pathvector#175]
Pathvectors bogon ASN feature would be far more useful if you could load the list of bogon ASNs from a file on a web server, like a CSV.

Pathvector generate should update this list, so it auto updates via crontab

**Comment by potvinp** [comment]
I support this feature. Would be handy to have instead of having to manually add them to configs across multiple hosts.

**Comment by natesales** [comment]
Bogon ASNs isn't really the right place for this. I've added a configurable blocklist that supports both ASNs and prefixes and can be fed by the Pathvector config file, pulled from a list of URLs, or included from a list of files.

Ref: 9aa6b2ebceb69f66b78f0a6780a17fcef0f4e6d2
