### ISSUE TITLE
OSPF Support

### ISSUE THREAD

**Issue by qbranchco** [natesales/pathvector#180]
Pathvector is amazing, but I am not 100% sure if it supports OSPF configs?

My use case is two Debian based BIRD routers, each connected to different IXPs.

Or is there a hacky way to get it working?

**Comment by hameno** [comment]
You can create the neccessary config as a separate manual_ospf.conf file. pathvector includes all manual_*.conf files.
I do it like this, although native support would be great

**Comment by natesales** [comment]
@hameno is spot on. Pathvector doesn't have built in syntax for OSPF (or any IGP for that matter). The focus is on inter AS routing, so IGPs are out of scope.
