### ISSUE TITLE
Dry run generate config with diff against current config

### ISSUE THREAD

**Issue by RX14** [natesales/pathvector#185]
Currently there is a "dry run" option for pathvector, but it would be lovely to dry-run pathvector generate and have pathvector show the diff between the files which would have been generated and the current config. This would help to see the details of how the bird config changes when a new config or even a new pathvector version is used.

**Comment by natesales** [comment]
Pathvector stores the output of a dry run in `cache-directory` (defaults to `/var/run/pathvector/cache/`), so you can already diff the output:

```sh
$ pathvector gen --dry-run
INFO[0000] Starting Pathvector 6.3.2                    
INFO[0005] BIRD config validation passed                
INFO[0005] Processed 8 peers in 5s                      
$ diff /var/run/pathvector/cache/ /etc/bird/
Only in /etc/bird/: AS34553_LGAS34553NET.conf
diff /var/run/pathvector/cache/bird.conf /etc/bird/bird.conf
1c1
< # Update time: 1689659925
---
> # Update time: 1689659872
Only in /etc/bird/: envvars
Only in /etc/bird/: protocols.json
```

If there were to be config changes other than removing a peer, you'd see the individual line diffs too.

**Comment by RX14** [comment]
I didn't realise this, thanks!
