### ISSUE TITLE
Adding AS6939 into the reject_transit_paths function

### ISSUE THREAD

**Issue by rapdodge** [natesales/pathvector#203]
I think it's better to adding 6939 into the reject_transit_paths function.

Right now, the reject_transit_paths function is like this.

```
function reject_transit_paths() {
  if (bgp_path ~ [174, 701, 702, 1239, 1299, 2914, 3257, 3320, 3356, 3491, 3549, 3561, 4134, 5511, 6453, 6461, 6762, 6830, 7018]) then _reject("transit path");
}
```

AS6939 can be said to be a tier 1 operator in IPv6. I know that AS6939 is not a tier 1 carrier in v4, if so, AS174 is also not a tier 1 carrier in IPv6, since they do not peer with AS6939.

**Comment by natesales** [comment]
We can't change this by adding AS6939 to the transit ASN list. HE peers openly, which is not the norm for "Tier 1" networks. Networks that use Pathvector to peer with IX route servers for example, would often have `filter-transit-asns` enabled on route server sessions, so we wouldn't want to reject AS6939 routes there. AS174 will never peer at an IX so we can confidently reject routes with AS174 in path.

(And not to be pedantic, but for clarity the AS6939/AS174 problem is IPv6: https://bgp.tools/kb/partitions)

**Comment by ElektronikerDev** [comment]
Hey,

thanks for your feedback on this. 
I completely agree with you that HE Transit mainly offers via IXPs and therefore the AS probably doesn't quite fit into this filter.

Then @rapdodge can simply add the AS 6939 himself via the variable "transit-asns" if he wants to ignore HE in the filter.

My pull request can therefore be closed and ignored :)

Have a nice weekend!

**Comment by rapdodge** [comment]
Thanks for the respond. This issue will be closed.
May God bless AS6939 and AS174 to be peer each other. If they not, so, they both aren't T1 ISP on IPv6
