### ISSUE TITLE
Single stack peer support

### ISSUE THREAD

**Issue by natesales** [natesales/pathvector#23]
BCG has reasonable single stack peer support, but I'm not confident that it's fully tested.

**Comment by hamptonmoore** [comment]
any specific issues you would assume happen? I use it with IPv6 only and have not seen any issues besides just a couple extra protocols that are unused for IPv4

**Comment by natesales** [comment]
Extra protocols would be the main thing, also validation errors for peers that only have IPv4 or IPv6, etc.

**Comment by natesales** [comment]
This has been addressed in v4, closing.
