### ISSUE TITLE
IRR list caching

### ISSUE THREAD

**Issue by netfreak98** [natesales/pathvector#41]
Would it be possible to cache already fetched prefix-lists? What I mean is fetching the lists once and reuse it on each session config which uses the same ASN and address family.

I'm peering with HE (AS6939) at many IXPs for example.. the time which is needed for each session to generate it's config is super long. 

What do you think?

Best,
Joey

**Comment by natesales** [comment]
I agree! Issue #19 covers a similar idea, is it ok to close this and we can track changes in #19?

**Comment by natesales** [comment]
Will address this in #19
