### ISSUE TITLE
/var/run/pathvector/cache/bird.conf: No such file or directory after reboot

### ISSUE THREAD

**Issue by peter-potvin** [natesales/pathvector#49]
After a fresh install of Debian 10, along with pathvector and all of it's prerequisites as well as a reboot of the system, the file `/var/run/pathvector/cache/bird.conf` and the directory `/var/run/pathvector/` can't be found by pathvector despite it existing after manually creating the directory after the original installation (another issue). The error message when attempting to run pathvector after a system reboot is below:
```
root@test-system-1:~# pathvector
FATA[0000] Create global BIRD output file: open /var/run/pathvector/cache/bird.conf: no such file or directory
```

It appears that during a reboot the system deletes the `/var/run/pathvector/` directory in its entirety, leaving the pathvector executable in an non-executable state due to the above directory not existing.

**Comment by natesales** [comment]
Thanks for the report! Fixed in v4.0.6 by creating the cache directory at runtime.
