### ISSUE TITLE
vrrp options not work

### ISSUE THREAD

**Issue by stefan6dev** [natesales/pathvector#51]
Hi,

we try to use vrrp on our config:
`vrrpInstance:
  state: primary
  interface: eth0.1234
  vrid: 1
  priority: 100
  vips:
    - 192.168.7.1/24
`
and got this error:
FATA[0000] YAML unmarshal: yaml: unmarshal errors:
  line 25: field vrrpInstance not found in type main.config

We have understand here some wrong in documentation?

**Comment by natesales** [comment]
Can I see the output of `pathvector --version` and your full YAML config?

**Comment by stefan6dev** [comment]
Hi,

INFO[0000] Pathvector version 4.0.6 (https://github.com/natesales/pathvector)

Complete config is here:
`asn: 56382
router-id: 185.133.208.16
source4: 185.133.208.16
source6: 2a07:59c6:ee00:208::16
accept-default: false
rtr-server: rtr.rpki.cloudflare.com:8282
irr-server: whois.radb.net
prefixes:
  - 45.152.126.0/24
  - 45.152.127.0/24
  - 185.133.208.0/24
  - 194.50.19.0/24
  - 2a07:59c6:ee00::/40
  - 2a07:59c6:ee02::/48
  - 2a07:59c6:e800::/38
  - 2a0f:5707:ab80::/44
vrrpInstance:
  state: primary
  interface: eth0.1234
  vrid: 1
  priority: 100
  vips:
    - 192.168.7.1/24
augments:
  accept4:
    - static4
  accept6:
    - static6
  statics:
    2a07:59c6:ee02:4::/64:       #glück
       fe80::7aec:7a1c:ae71:7c54
`

**Comment by natesales** [comment]
Thanks for the update! The VRRP config block should live under the `vrrp` key, and be a list instead of a map.

Here's an example:

```yaml
vrrp:
  - state: primary
    interface: eth0.1234
    vrid: 1
    priority: 100
    vips:
      - 192.168.7.1/24
```

**Comment by stefan6dev** [comment]
Hi, thanks, that is working!
