### ISSUE TITLE
static routes to vlan

### ISSUE THREAD

**Issue by stefan6dev** [natesales/pathvector#52]
Hi,

for our setup we need to set bird static routes for example an /29 IPv4 subnet into an VLAN.

This is at the moment not implemented. Is there an option to add that static on the config?

BR
Stefan

**Comment by natesales** [comment]
Static routes can be configured as [augments](https://pathvector.io/configuration/options.html#augments), but there isn't currently a way to specify an interface for the route. I see the use case though, so I'll add it to the roadmap for an upcoming release.

An example of how static routes currently work:

```yaml:
augments:
  statics:
    "192.0.2.0/24": "203.0.113.1"
```
