### ISSUE TITLE
Annouce-Community invalid

### ISSUE THREAD

**Issue by guyaevans** [natesales/pathvector#58]
Hi
When setting a community in ``` annouce-community ``` I get the following error ``` FATA[0000] Invalid announce community: 211486,101 ```

Config:
```
    announce-communities:
      - 211486,101
```

Not sure what the fix would be, thanks for the great work

**Comment by natesales** [comment]
AS211486 would overflow a 16 bit integer so you'll have to use BGP large communities. Pathvector follows [RFC 8092](https://datatracker.ietf.org/doc/html/rfc8092) so the format for large communities is a string composed of 3 32 bit integers separated by colons. For example, you could do `211486:0:101`.

**Comment by natesales** [comment]
Closed
