### ISSUE TITLE
Feature request: Specify to use authoritative IRR DBs when using NTT's RR

### ISSUE THREAD

**Issue by potvinp** [natesales/pathvector#67]
Would be nice to be able to filter out any IRR records from non-auth route registries such as RADB when using the default NTT route registry for IRR validation.

**Comment by natesales** [comment]
Added in b3424743a119961c95bcb4741358bde4b4790ebf

You can now add the `bgpq-args` key at the root of your config to pass additional arguments to bgpq4 invocation. For example: `bgpq-args: -S RADB,NTTCOM`
