### ISSUE TITLE
Static Route not import to kernel

### ISSUE THREAD

**Issue by steveyiyo** [natesales/pathvector#97]
**Describe the bug**
Static Route does not work

**Environment**
```
Pathvector Version: Pathvector 5.9.2 commit d47a7a8e516c6a258fbb5e071bac4dac221854a6 date 2022-01-16T21:56:59Z / No plugins
Linux Kernel: 5.10.0-10-amd64
Routing Daemon Version: BIRD 2.0.7
```

**To Reproduce**
```
augments:
  statics:
    "103.x.124.0/27": "103.x.x.35"
    "103.x.124.32/28": "103.x.x.29" 
    "103.x.124.112/29": "103.x.x.35"
```

**Expected behavior**
BIRD should export to the kernel, but it not.
After checking the BIRD configure which generate by pathvector, I see the bird rejectd the static4 protocol route.

```
protocol kernel {
  scan time 10;
  
  
  ipv4 {
    export filter {
      
      
      
      if source = RTS_STATIC && proto = "static4" then {
        accept;
      } else if source = RTS_BGP then {
        krt_prefsrc = 103.x.x.x;
        accept;
      }
      reject;
      
      
      
    };
  };
  
}
```

manually modified it to `if source = RTS_STATIC then {` can work.

**Comment by natesales** [comment]
Static routes defined in BIRD aren't installed in the kernel FIB by default. If you want that behavior, add them to the `accept4` and `accept6` protocol augments: https://pathvector.io/docs/configuration#accept4
