### ISSUE TITLE
No IPv4 Prefix will discontinue the pathvector

### ISSUE THREAD

**Issue by steveyiyo** [natesales/pathvector#98]
**Environment**
Pathvector Version: Pathvector 5.9.2 commit d47a7a8e516c6a258fbb5e071bac4dac221854a6 date 2022-01-16T21:56:59Z / No plugins
Linux Kernel: 5.10.0-10-amd64
Routing Daemon Version: BIRD 2.0.7

**To Reproduce**
If Peer has no IPv4 Prefixes but has an IPv4 Session, the pathvector will discontinue.
```
root@tpe:/etc/bird# pathvector generate
INFO[0000] Processing AS38855 STUIX-RS                  
INFO[0000] Processing AS6939 HE                         
INFO[0000] Processing ASxxx XXX                     
INFO[0003] Processing AS210528 Vincent                  
FATA[0004] peer has IPv4 session(s) but no IPv4 prefixes 
```

**Expected behavior**

It should reject all IPv4 routes.

https://github.com/natesales/pathvector/blob/2eccee5b19a5461af78d9da794f7e40af4f08433/internal/irr/irr.go#L76

**Comment by natesales** [comment]
Updated in v5.10.0

**Comment by steveyiyo** [comment]
@natesales Thanks for fixing it, but there still has a bug that causes BIRD validation to fail.

```
INFO[0008] Processing AS210528 Vincent                  
WARN[0010] peer has IPv4 session(s) but no IPv4 prefixes 
INFO[0011] Processing AS16509 AWS                       
FATA[0015] BIRD validation error:
            bgp_community.add((60614,10005));
            if (net ~ AS210528_VINCENT_PFX_v4) then { accept; } else { _reject("not in IRR prefix set"); }
                      ^ syntax error, unexpected CF_SYM_UNDEFINED
            accept; 
```

It should reject all IPv4 routes.

**Comment by steveyiyo** [comment]
Thanks @natesales , It has been fixed :)
